name: Android CI

on:
  push:
    branches: [ "main" ] # تأكد أن اسم الفرع عندك هو main أو master
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: set up JDK 17 # نستخدم نسخة أحدث للتوافق
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build APK
      run: ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: my-app-apk
        path: app/build/outputs/apk/debug/app-debug.apk
